//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TorrentDownloaderDBModel", "ShowEpisode", "Show", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DatabaseAccess.Show), "Episode", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DatabaseAccess.Episode))]

#endregion

namespace DatabaseAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TorrentDownloaderEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TorrentDownloaderEntities object using the connection string found in the 'TorrentDownloaderEntities' section of the application configuration file.
        /// </summary>
        public TorrentDownloaderEntities() : base("name=TorrentDownloaderEntities", "TorrentDownloaderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TorrentDownloaderEntities object.
        /// </summary>
        public TorrentDownloaderEntities(string connectionString) : base(connectionString, "TorrentDownloaderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TorrentDownloaderEntities object.
        /// </summary>
        public TorrentDownloaderEntities(EntityConnection connection) : base(connection, "TorrentDownloaderEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Show> Shows
        {
            get
            {
                if ((_Shows == null))
                {
                    _Shows = base.CreateObjectSet<Show>("Shows");
                }
                return _Shows;
            }
        }
        private ObjectSet<Show> _Shows;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Episode> Episodes
        {
            get
            {
                if ((_Episodes == null))
                {
                    _Episodes = base.CreateObjectSet<Episode>("Episodes");
                }
                return _Episodes;
            }
        }
        private ObjectSet<Episode> _Episodes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shows EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShows(Show show)
        {
            base.AddObject("Shows", show);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Episodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEpisodes(Episode episode)
        {
            base.AddObject("Episodes", episode);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TorrentDownloaderDBModel", Name="Episode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Episode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Episode object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Episode CreateEpisode(global::System.Int32 id)
        {
            Episode episode = new Episode();
            episode.Id = id;
            return episode;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String torrentFile720
        {
            get
            {
                return _torrentFile720;
            }
            set
            {
                OntorrentFile720Changing(value);
                ReportPropertyChanging("torrentFile720");
                _torrentFile720 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("torrentFile720");
                OntorrentFile720Changed();
            }
        }
        private global::System.String _torrentFile720;
        partial void OntorrentFile720Changing(global::System.String value);
        partial void OntorrentFile720Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String torrentFile1080
        {
            get
            {
                return _torrentFile1080;
            }
            set
            {
                OntorrentFile1080Changing(value);
                ReportPropertyChanging("torrentFile1080");
                _torrentFile1080 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("torrentFile1080");
                OntorrentFile1080Changed();
            }
        }
        private global::System.String _torrentFile1080;
        partial void OntorrentFile1080Changing(global::System.String value);
        partial void OntorrentFile1080Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String torrentFileHD
        {
            get
            {
                return _torrentFileHD;
            }
            set
            {
                OntorrentFileHDChanging(value);
                ReportPropertyChanging("torrentFileHD");
                _torrentFileHD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("torrentFileHD");
                OntorrentFileHDChanged();
            }
        }
        private global::System.String _torrentFileHD;
        partial void OntorrentFileHDChanging(global::System.String value);
        partial void OntorrentFileHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private global::System.String _num;
        partial void OnnumChanging(global::System.String value);
        partial void OnnumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Downloaded
        {
            get
            {
                return _Downloaded;
            }
            set
            {
                OnDownloadedChanging(value);
                ReportPropertyChanging("Downloaded");
                _Downloaded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Downloaded");
                OnDownloadedChanged();
            }
        }
        private global::System.Boolean _Downloaded = false;
        partial void OnDownloadedChanging(global::System.Boolean value);
        partial void OnDownloadedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TorrentDownloaderDBModel", "ShowEpisode", "Show")]
        public Show Show
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("TorrentDownloaderDBModel.ShowEpisode", "Show").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("TorrentDownloaderDBModel.ShowEpisode", "Show").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Show> ShowReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Show>("TorrentDownloaderDBModel.ShowEpisode", "Show");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Show>("TorrentDownloaderDBModel.ShowEpisode", "Show", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TorrentDownloaderDBModel", Name="Show")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Show : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Show object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Show CreateShow(global::System.Int32 id)
        {
            Show show = new Show();
            show.Id = id;
            return show;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String prettyName
        {
            get
            {
                return _prettyName;
            }
            set
            {
                OnprettyNameChanging(value);
                ReportPropertyChanging("prettyName");
                _prettyName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("prettyName");
                OnprettyNameChanged();
            }
        }
        private global::System.String _prettyName;
        partial void OnprettyNameChanging(global::System.String value);
        partial void OnprettyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String genre
        {
            get
            {
                return _genre;
            }
            set
            {
                OngenreChanging(value);
                ReportPropertyChanging("genre");
                _genre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("genre");
                OngenreChanged();
            }
        }
        private global::System.String _genre;
        partial void OngenreChanging(global::System.String value);
        partial void OngenreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TorrentDownloaderDBModel", "ShowEpisode", "Episode")]
        public EntityCollection<Episode> Episodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Episode>("TorrentDownloaderDBModel.ShowEpisode", "Episode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Episode>("TorrentDownloaderDBModel.ShowEpisode", "Episode", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
